# Motor
MOTOR_LEFT_FORWARD = 20
MOTOR_LEFT_BACK = 21
MOTOR_RIGHT_FORWARD = 19
MOTOR_RIGHT_BACK = 26
MOTOR_LEFT_PWM = 16
MOTOR_RIGHT_PWM = 13

# Patrol Sensors
PATROL_LEFT_1 = 3
PATROL_LEFT_2 = 5
PATROL_RIGHT_1 = 4
PATROL_RIGHT_2 = 18
